"""Add reviewer_name to CustomerReview

Revision ID: 4e18d0c996d9
Revises: f32643ffd99d
Create Date: 2026-05-19 14:08:33.922509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e18d0c996d9'
down_revision = 'f32643ffd99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewer_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_reviews', schema=None) as batch_op:
        batch_op.drop_column('reviewer_name')

    # ### end Alembic commands ###
