"""tembo

Revision ID: d574408a674d
Revises: 387087cfa75c
Create Date: 2025-12-29 23:42:04.771683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd574408a674d'
down_revision: Union[str, Sequence[str], None] = '387087cfa75c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('known_for', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('safari_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('total_nights', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activities', sa.JSON(), nullable=True),
    sa.Column('meals', sa.JSON(), nullable=True),
    sa.Column('park_name', sa.String(length=100), nullable=False),
    sa.Column('park_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['safari_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package_itineraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('itinerary_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['safari_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safari_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['safari_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itinerary_accommodations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('accommodation_name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['package_itineraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('pax_2_price', sa.Float(), nullable=False),
    sa.Column('pax_4_price', sa.Float(), nullable=False),
    sa.Column('pax_6_price', sa.Float(), nullable=False),
    sa.Column('pax_8_price', sa.Float(), nullable=False),
    sa.Column('single_supplement', sa.Float(), nullable=True),
    sa.Column('child_price', sa.Float(), nullable=True),
    sa.Column('includes', sa.JSON(), nullable=True),
    sa.Column('excludes', sa.JSON(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['itinerary_id'], ['package_itineraries.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['safari_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safari_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['safari_reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('safari_comments')
    op.drop_table('package_prices')
    op.drop_table('itinerary_accommodations')
    op.drop_table('safari_reviews')
    op.drop_table('package_itineraries')
    op.drop_table('package_days')
    op.drop_table('safari_packages')
    op.drop_table('parks')
    # ### end Alembic commands ###
